### ISSUE TITLE
Porting 'fx': SIGSEGV

### ISSUE THREAD

**Issue by dustin-ward** [ZOSOpenTools/wharf#41]
Runtime error when trying to port [fx](https://github.com/antonmedv/fx)

```
> wharf -v ./fx
Import path set to: /home/dustinw/Work/Porting/fx/wharf_port
Build errors occurred in: github.com/antonmedv/fx
        main.go:181:44: theme.TermOutput.ColorProfile undefined (type *termenv.Output has no field or method ColorProfile)
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2c addr=0xf7c72a0 pc=0xf7c72a0]

goroutine 1 [running]:
github.com/zosopentools/wharf/internal/porting.initProcFlags(...)
        /jenkins/workspace/Port-Build/wharf/wharf/internal/porting/states.go:36
github.com/zosopentools/wharf/internal/porting.port(0xc00185c820, 0xc00048d860)
        /jenkins/workspace/Port-Build/wharf/wharf/internal/porting/port.go:401 +0xb02
github.com/zosopentools/wharf/internal/porting.run({0xc0004203e0, 0x1, 0x1}, 0xc00048d860)
        /jenkins/workspace/Port-Build/wharf/wharf/internal/porting/port.go:173 +0x2d8
github.com/zosopentools/wharf/internal/porting.Port({0xc0004203e0, 0x1, 0x1}, 0xc00048d860)
        /jenkins/workspace/Port-Build/wharf/wharf/internal/porting/port.go:90 +0x4aa
main.main1(...)
        /jenkins/workspace/Port-Build/wharf/wharf/main.go:147
main.main()
        /jenkins/workspace/Port-Build/wharf/wharf/main.go:119 +0xd48
```

**Comment by jlee3227** [comment]
Resolved with the latest version of wharf
